---
- name: 'update all pacakages to latest'
  yum: name=* state=latest

- name: 'install EPEL repo'
  yum: name=epel-release state=present

- name: 'install package dependencies'
  yum: name={{ item }} state=present
  with_items:
    - dejavu-sans-fonts
    - dejavu-serif-fonts
    - git
    - pycairo
    - python-django
    - python-django-tagging
    - python-twisted-core
    - python-whisper
    - pytz

- name: 'clone github graphite-web repo'
  git: repo=https://github.com/graphite-project/graphite-web.git dest=/home/vagrant/graphite

- name: 'install graphite webapp'
  command: python setup.py install chdir=graphite 
