---
- name: 'install carbon/graphite dependencies'
  yum: name={{ item }} state=present
  with_items:
    - dejavu-sans-fonts
    - dejavu-serif-fonts
    - git
    - pycairo
    - pyparsing
    - python-django
    - python-django-tagging
    - python-twisted-core
    - python-whisper
    - pytz
    - uwsgi
    - uwsgi-plugin-python

- name: 'clone github graphite-web repo'
  git: repo=https://github.com/graphite-project/graphite-web.git dest=/home/vagrant/graphite

- name: 'install graphite webapp'
  command: python setup.py install chdir=graphite 

- name: 'create graphite group'
  group: name=graphite state=present

- name: 'create graphite user'
  user: name=graphite group=graphite

- name: 'change app dir owner'
  file: path=/opt/graphite owner=graphite group=graphite state=directory recurse=yes

- name: 'configure webapp local settings'
  copy: src=local_settings.py dest=/opt/graphite/webapp/graphite owner=graphite group=graphite

# ansible django_manage module not compatible
- name: 'initialize webapp (django) db'
  command: django-admin syncdb --pythonpath=/opt/graphite/webapp --settings=graphite.settings --noinput
  become: yes
  become_user: graphite

- name: 'configure uwsgi to serve graphite'
  copy: src=graphite.ini dest=/etc/uwsgi.d

- name: 'set uwsgi file ownership'
  file: path=/etc/uwsgi.d/graphite.ini owner=graphite group=graphite

- name: 'enable and start uwsgi service'
  service: name=uwsgi enabled=yes state=restarted

- name: 'add graphite site to nginx conf'
  copy: src=graphite.conf dest=/etc/nginx/conf.d

- name: 'reload nginx service'
  service: name=nginx state=restarted
