#!/bin/bash
#
# Initialize Ansible communication on EM7 hosts.
# This has to be done before ansible-playbook can be used.

usage () {
    echo "usage: $(basename $0) HOST"
    echo ""
    echo "Set HOST up for ansible control via key-based SSH access"
    echo -e "\nHOST should be a host or group name from the Ansible inventory."
    exit 1
}

[[ $# == 1 ]] || usage
HOST=$1

INVENTORY=./hosts
SSH_KEY=$(cat /home/vagrant/.ssh/id_rsa.pub)
ANSIBLE="ansible $HOST -u root"
ASK_PASS=-k

# For this session, disable checking of keys in known_hosts
export ANSIBLE_HOST_KEY_CHECKING=False

if [ $HOST = "em7" ]; then
    # python-simplejson is needed for ansible responses on CentOS 5
    # The user has to enter the root password to get things going
    $ANSIBLE $ASK_PASS -m raw -a "yum install -y python-simplejson"

    # Disable password prompt for next operation
    ASK_PASS=
fi

# Now install the SSH key on the remotes.
$ANSIBLE $ASK_PASS -m authorized_key -a "user=root key=\"$SSH_KEY\""

echo "Done."
