#!/bin/bash
#
# Initialize Ansible communication on EM7 hosts.
# This has to be done before ansible-playbook can be used.

usage () {
    echo "usage: $(basename $0) HOST"
    echo ""
    echo "Set HOST up for ansible control via key-based SSH access"
    exit 1
}

[[ $# == 1 ]] || usage
HOST=$1

INVENTORY=./hosts
SSH_KEY=$(cat /home/vagrant/.ssh/id_rsa.pub)
ANSIBLE="ansible $HOST -i $INVENTORY -u root"

# For this session, disable checking of keys in known_hosts
export ANSIBLE_HOST_KEY_CHECKING=False

# python-simplejson is needed for ansible responses on CentOS 5
# The user has to enter the root password to get things going
echo -e "\nEnter the root password for host(s) \"$HOST\""
$ANSIBLE -k -m raw -a "yum install -y python-simplejson"

# Now install the SSH key on the remotes
$ANSIBLE -m authorized_key -a "user=root key=\"$SSH_KEY\""

echo "Done."
echo "You can verify with \"ansible -u root -i hosts all -m ping\"\n"
