---
- hosts: all
  tasks:
  - name: update apt cache
    apt: update_cache=yes

  - name: install curl
    apt: name=curl state=present

  - name: install git
    apt: name=git state=present

  - name: write git config
    template: src=gitconfig dest=/home/vagrant/.gitconfig

  - name: install make (for fpm)
    apt: name=make state=present

  - name: install ruby-dev (for fpm)
    apt: name=ruby-dev state=present

  - name: install fpm
    gem: name=fpm state=present

  - name: install vim
    apt: name=vim state=present
