---
- name: add EPEL yum repo
  yum: pkg=epel-release

- name: install ansible
  yum: pkg=ansible

- name: install sshpass for EM7 setup support
  yum: pkg=sshpass
  
- name: copy ansible playbook and support files
  copy: src=ansible dest=/home/vagrant owner=vagrant

- name: make scripts executable
  file: path=ansible/em7-setup mode=0755
  
- name: create ansible SSH key
  command: /usr/bin/ssh-keygen -N '' -f /home/vagrant/.ssh/id_rsa creates=/home/vagrant/.ssh/id_rsa
  sudo: yes
  sudo_user: vagrant

- name: install mtools for auto-deploy
  yum: pkg=mtools

- name: install fabric for auto-deploy
  yum: pkg=fabric

- name: install python-requests for vCenter auto-deploy
  yum: pkg=python-requests

- name: install pip for pysphere install
  yum: pkg=python-pip

- name: install pysphere for vCenter auto-deploy
  pip: name=pysphere

- name: place automated deployment code
  unarchive: src=/vagrant/automated_deployment.tgz dest=/home/vagrant owner=vagrant group=vagrant copy=no
