# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # May 2016: Travis uses Ubuntu 12.04.05 for Fugue builds
  config.vm.box = "hashicorp/precise64"

  # make SSH keys for git available
#  config.vm.synced_folder "/Users/scott/.ssh", "/home/vagrant/.ssh"
  config.vm.synced_folder "/Users/scott/fugue/fugue-client", "/home/vagrant/fugue-client"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = 'provisioning/fugue-travis.yml'
    ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
    ansible.sudo = true
  end
end
