# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # May 2016: Travis uses Ubuntu 12.04.05 for Fugue builds
  config.vm.define "u12" do |u14|
      u14.vm.box = "ubuntu/precise64"
  end

  config.vm.define "c6", autostart: false do |c6|
      c6.vm.box = "bento/centos-6.7"
  end

  # make SSH keys for git available
  # config.vm.synced_folder "/Users/scott/.ssh", "/home/vagrant/.ssh"

  config.vm.synced_folder "/Users/scott/fugue", "/home/vagrant/fugue"

  # config.vm.provision "ansible" do |ansible|
  #   ansible.playbook = 'provisioning/fugue-travis.yml'
  #   ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
  #   ansible.sudo = true
  # end
end
